python3 Codefiles/Controller.py>./controller.logs &
wait 5 &
python3 Codefiles/Node1.py>./node1.logs &
wait 5 &
python3 Codefiles/Node2.py>./node2.logs &
wait 5 &
python3 Codefiles/Node3.py>./node3.logs &
wait 5 &
python3 Codefiles/Node4.py>./node4.logs &
wait 5 &
python3 Codefiles/Node5.py>./node5.logs &